### ISSUE TITLE
Size of WeakLearners must be longer than eval_set

### ISSUE THREAD

**Issue by thomaswsu** [thomaswsu/Stochastic-Gradient-Boosting-and-Adaboost#2]
In the run() function in functions.py, if the array length of Weak_Learners is smaller that eval_set, there is a out bounds index error. I believe this is because for every row in eval_set, there needs to be a row in Weak_Learners. In other words Weak_Learners.size[0] >= eval_set.size[0], or else there will be an out of bounds error. 

This means we can't run the model unless the training data is at least as big as the testing data.

Steps to reproduce:
1. Train WeakLearners with 10% of data.
2. Test WeakLearners with 90% of data.

**Comment by ellinj2** [comment]
So eval_set should be the data to be compared. For example, if you put in Xtrain, you would use Ytrain as eval_set to compare the output from Xtrain

**Comment by thomaswsu** [comment]
I believe I currently have it set up the way that you specified in your comment. For example in experiment.ipynb I have: 

`test_local_accuracies.append(run(Weak_Learners, Xtest, Ytest_classes[i], H_test, weights))`

**Comment by thomaswsu** [comment]
Closed
